# Generated by Django 6.0.6 on 2026-08-17 05:40

from django.db import migrations

def seed_data(apps, schema_editor):
    Roles = apps.get_model('core', 'Roles')
    Roles.objects.bulk_create([
        Roles(role_name='Admin', description='Administrator with full access'),
        Roles(role_name='Clinician', description='Healthcare professional'),
        Roles(role_name='Patient', description='Patient receiving rehabilitation'),
        Roles(role_name='Receptionist', description='Front desk scheduling and management'),
    ])

    Assessment_Metrics = apps.get_model('core', 'Assessment_Metrics')
    Assessment_Metrics.objects.bulk_create([
        Assessment_Metrics(metric_name='Mobility Score', unit='score', min_value=0.0, max_value=100.0),
        Assessment_Metrics(metric_name='Pain Level', unit='1-10 scale', min_value=1.0, max_value=10.0),
        Assessment_Metrics(metric_name='Range of Motion', unit='degrees', min_value=0.0, max_value=360.0),
        Assessment_Metrics(metric_name='Strength Score', unit='score', min_value=0.0, max_value=5.0),
    ])

def reverse_seed_data(apps, schema_editor):
    Roles = apps.get_model('core', 'Roles')
    Roles.objects.all().delete()
    
    Assessment_Metrics = apps.get_model('core', 'Assessment_Metrics')
    Assessment_Metrics.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
